image: eu.gcr.io/ligatus-prod-public-registry/generic-build-agent:latest

variables:
  ARTIFACT_DIR: "bin"

stages:
  - build

build:
  stage: build
  script:
  - rm -f ~/.m2/settings.xml
  - build/mvn -DskipTests clean package --quiet
  - tar -zcvf ${ARTIFACT_DIR}.tar.gz $ARTIFACT_DIR
  - gsutil -m cp ${ARTIFACT_DIR}.tar.gz gs://lqm-artifact/${CI_PROJECT_NAME}/${CI_COMMIT_SHA}

