image: eu.gcr.io/ligatus-prod-public-registry/generic-build-agent:latest

variables:
  ARTIFACT: "artifact.tar.gz"

stages:
  - build

build:
  stage: build
  script:
  - rm -f ~/.m2/settings.xml
  - build/mvn -DskipTests clean package --quiet
  - cd ${CI_PROJECT_DIR}/..
  - tar -zcf ${CI_PROJECT_DIR}/../${ARTIFACT} ${CI_PROJECT_NAME}
  - gsutil -m cp ${CI_PROJECT_DIR}/../${ARTIFACT} gs://lqm-artifact/${CI_PROJECT_NAME}/${CI_COMMIT_SHA}
